#
# GitHub Actions Workflow: Extreme Performance RDP
#
# Description:
# This workflow sets up a highly optimized RDP session on a GitHub-hosted Windows runner.
# It applies aggressive system, CPU, network, and RDP-specific tweaks designed for
# a powerful and STABLE experience, prioritizing smoothness and consistency over raw,
# potentially unstable, speed.
#
name: Extreme Performance RDP Tunnel (Fixed)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 359 # Slightly less than the 6-hour max

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure Auto-Login Administrator
      shell: powershell
      run: |
        $username = "rdpadmin"
        $password = "UltraFast2024!"
        Write-Host "[*] Configuring auto-login user: $username"
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
        
        # Create user if it doesn't exist, or set password if it does
        if (Get-LocalUser -Name $username -ErrorAction SilentlyContinue) {
            Write-Host "  - User '$username' already exists. Setting password."
            Set-LocalUser -Name $username -Password $securePassword
        } else {
            Write-Host "  - Creating new user '$username'."
            New-LocalUser -Name $username -Password $securePassword -FullName "RDP Admin" -Description "Temp RDP User"
        }
        
        # Add user to necessary groups
        Add-LocalGroupMember -Group "Administrators" -Member $username
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username
        
        # Configure registry for automatic login
        $regPath = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon"
        Set-ItemProperty -Path $regPath -Name "DefaultUserName" -Value $username
        Set-ItemProperty -Path $regPath -Name "DefaultPassword" -Value $password
        Set-ItemProperty -Path $regPath -Name "AutoAdminLogon" -Value "1"
        Set-ItemProperty -Path $regPath -Name "ForceAutoLogon" -Value "1"

        # Disable lock screen
        $personalizationPath = "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization"
        New-Item -Path $personalizationPath -Force | Out-Null
        Set-ItemProperty -Path $personalizationPath -Name "NoLockScreen" -Value 1 -Force

        Write-Host "[SUCCESS] Auto-login configured."
        Write-Host "--- RDP CREDENTIALS ---"
        Write-Host "Username: $username"
        Write-Host "Password: $password"
        Write-Host "-----------------------"

    - name: Apply Ultimate Performance Optimizations
      shell: powershell
      run: |
        Write-Host "[*] Applying STABLE system, network, and RDP optimizations..."

        # --- 1. Maximize CPU Performance ---
        Write-Host "  - Activating Ultimate Performance power plan..."
        $powercfgOutput = powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61
        $ultimatePerformanceGuid = ($powercfgOutput -split ' ')[3]
        powercfg /s $ultimatePerformanceGuid
        powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PROCTHROTTLEMAX 100
        powercfg /setdcvalueindex SCHEME_CURRENT SUB_PROCESSOR PROCTHROTTLEMAX 100
        
        Write-Host "  - Disabling CPU Core Parking..."
        powercfg /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR CPMINCORES 100
        powercfg /setdcvalueindex SCHEME_CURRENT SUB_PROCESSOR CPMINCORES 100
        
        Write-Host "  - Setting CPU scheduling for foreground apps..."
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\PriorityControl" -Name "Win32PrioritySeparation" -Value 26 -Force
        
        Write-Host "  - Disabling system-wide Power Throttling..."
        $powerThrottlingPath = "HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling"
        New-Item -Path $powerThrottlingPath -Force | Out-Null
        Set-ItemProperty -Path $powerThrottlingPath -Name "PowerThrottlingOff" -Value 1 -Force

        # --- 2. Aggressive Network Optimizations for Low Latency ---
        Write-Host "  - Applying aggressive TCP settings for low latency..."
        netsh int tcp set global autotuninglevel=normal # Use 'normal' for stability over 'experimental'
        netsh int tcp set supplemental template=internet congestionprovider=ctcp
        netsh int tcp set global rss=enabled
        netsh int tcp set global rsc=enabled
        netsh int tcp set global ecncapability=disabled
        netsh int tcp set global timestamps=disabled
        
        Write-Host "  - Disabling network throttling..."
        Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile" -Name "NetworkThrottlingIndex" -Value 0xFFFFFFFF -Force
        
        # --- 3. Deep RDP Protocol & Service Optimization ---
        Write-Host "  - Configuring RDP for performance over quality..."
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fSingleSessionPerUser" -Value 0 -Force
        
        $policyPath = "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services"
        New-Item -Path $policyPath -Force | Out-Null
        Set-ItemProperty -Path $policyPath -Name "bEnforceGpuPreference" -Value 1 -Type DWord -Force
        Set-ItemProperty -Path $policyPath -Name "MaxColorDepth" -Value 16 -Type DWord -Force
        Set-ItemProperty -Path $policyPath -Name "fUseHardwareCodec" -Value 1 -Type DWord -Force

        Write-Host "  - Enabling UDP transport for a more responsive RDP experience..."
        Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name "fEnableUdp" -Value 1 -Type DWord -Force
        
        $clientPolicyPath = "HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\Client"
        New-Item -Path $clientPolicyPath -Force | Out-Null
        Set-ItemProperty -Path $clientPolicyPath -Name "fClientDisableUdp" -Value 0 -Type DWord -Force
        Set-ItemProperty -Path $clientPolicyPath -Name "fClientDisableClipboard" -Value 1 -Type DWord -Force
        Set-ItemProperty -Path $clientPolicyPath -Name "fClientDisableDriveRedirection" -Value 1 -Type DWord -Force
        Set-ItemProperty -Path $clientPolicyPath -Name "fClientDisablePrinterRedirection" -Value 1 -Type DWord -Force

        # --- 4. System-Wide Debloating & Responsiveness Tweaks ---
        Write-Host "  - Disabling non-essential and performance-draining services..."
        $servicesToDisable = @(
            "SysMain", "Print Spooler", "BITS", "diagtrack", "MapsBroker", "WbioSrvc", 
            "lfsvc", "Themes", "TabletInputService", "dmwappushservice", "WwanSvc", 
            "XblAuthManager", "XblGameSave", "wisvc", "wuauserv", "SecurityHealthService", 
            "wscsvc", "Sense", "RemoteRegistry", "Fax", "TrkWks", "PushToInstall"
        )
        foreach ($service in $servicesToDisable) {
            try {
                Get-Service -Name $service | Stop-Service -Force -ErrorAction SilentlyContinue
                Get-Service -Name $service | Set-Service -StartupType Disabled -ErrorAction SilentlyContinue
            } catch {}
        }

        Write-Host "  - Optimizing memory management..."
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" -Name "DisablePagingExecutive" -Value 1 -Force
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" -Name "LargeSystemCache" -Value 0 -Force
        
        Write-Host "  - Disabling Windows Defender real-time monitoring..."
        Set-MpPreference -DisableRealtimeMonitoring $true -ErrorAction SilentlyContinue
        
        # NOTE: Disabling CPU security mitigations has been removed to improve system stability and prevent freezes.
        
        Write-Host "[SUCCESS] All STABLE performance optimizations have been applied."

    - name: Disable Scheduled Tasks
      shell: powershell
      run: |
        Write-Host "[*] Disabling performance-impacting scheduled tasks..."
        $tasksToDisable = @(
            "\Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser",
            "\Microsoft\Windows\Application Experience\ProgramDataUpdater",
            "\Microsoft\Windows\Customer Experience Improvement Program\Consolidator",
            "\Microsoft\Windows\Customer Experience Improvement Program\KernelCeipTask",
            "\Microsoft\Windows\Customer Experience Improvement Program\UsbCeip",
            "\Microsoft\Windows\DiskDiagnostic\Microsoft-Windows-DiskDiagnosticDataCollector",
            "\Microsoft\Windows\Maintenance\WinSAT",
            "\Microsoft\Windows\Windows Error Reporting\QueueReporting",
            "\Microsoft\Windows\Windows Defender\Windows Defender Cache Maintenance",
            "\Microsoft\Windows\Windows Defender\Windows Defender Cleanup",
            "\Microsoft\Windows\Windows Defender\Windows Defender Scheduled Scan",
            "\Microsoft\Windows\Windows Defender\Windows Defender Verification",
            "\Microsoft\Windows\UpdateOrchestrator\Schedule Scan",
            "\Microsoft\Windows\UpdateOrchestrator\UpdateAssistant",
            "\Microsoft\Windows\Shell\FamilySafetyUpload"
        )
        foreach ($taskFullPath in $tasksToDisable) {
            # Use the native PowerShell cmdlets for scheduled tasks, which is more robust.
            # This avoids errors by checking if the task exists before trying to disable it.
            try {
                $taskName = Split-Path $taskFullPath -Leaf
                $taskPath = (Split-Path $taskFullPath -Parent) + "\"
                $task = Get-ScheduledTask -TaskPath $taskPath -TaskName $taskName -ErrorAction SilentlyContinue
                if ($task) {
                    $task | Disable-ScheduledTask
                }
            } catch {
                # This block will catch any other unexpected errors but will not fail the step.
                Write-Warning "Could not disable task '$taskFullPath': $_"
            }
        }
        Write-Host "[SUCCESS] Key scheduled tasks disabled."

    - name: Start RDP Service and Tunnel
      shell: powershell
      run: |
        Write-Host "[*] Starting services and tunnel with HIGH priority for stability..."
        
        # Enable RDP Firewall Rule for both TCP and UDP
        New-NetFirewallRule -DisplayName "Allow RDP" -Direction Inbound -Action Allow -Protocol TCP -LocalPort 3389
        New-NetFirewallRule -DisplayName "Allow RDP UDP" -Direction Inbound -Action Allow -Protocol UDP -LocalPort 3389
        
        Start-Service -Name "TermService"
        Start-Sleep -s 5
        try {
            $rdpService = Get-CimInstance Win32_Service | Where-Object {$_.Name -eq 'TermService'}
            if ($rdpService.ProcessId -ne 0) {
                # STABILITY FIX: Use 'High' priority instead of 'Realtime' to prevent system freezes.
                (Get-Process -Id $rdpService.ProcessId).PriorityClass = 'High'
                Write-Host "[SUCCESS] RDP service (TermService) priority set to HIGH."
            } else {
                Write-Host "[WARNING] RDP Service (TermService) has a PID of 0. Cannot set priority."
            }
        } catch {
            Write-Host "[WARNING] Could not set RDP service to high priority. This is non-fatal."
        }
        
        Write-Host "[*] Downloading and starting Playit.gg tunnel..."
        $releaseInfo = Invoke-RestMethod -Uri "https://api.github.com/repos/playit-cloud/playit-agent/releases/latest"
        $assetName = 'playit-windows-x86_64.exe'
        $downloadUrl = $releaseInfo.assets | Where-Object { $_.name -eq $assetName } | Select-Object -ExpandProperty browser_download_url
        
        if (-not $downloadUrl) {
            Write-Host "[ERROR] Could not find the download URL for '$assetName' in the latest release." -ForegroundColor Red
            Write-Host "  - Available assets are:"
            $releaseInfo.assets | ForEach-Object { Write-Host "    - $($_.name)" }
            exit 1
        }
        
        Write-Host "  - Downloading from direct URL: $downloadUrl"
        curl.exe -L -o playit.exe $downloadUrl
        
        if (-not (Test-Path -Path ".\playit.exe")) {
            Write-Host "[ERROR] playit.exe not found after download attempt." -ForegroundColor Red
            exit 1
        }
        $fileSize = (Get-Item -Path ".\playit.exe").Length
        if ($fileSize -lt 1000000) {
             Write-Host "[ERROR] Downloaded file is too small ($fileSize bytes). Download likely failed." -ForegroundColor Red
             exit 1
        }
        Write-Host "[SUCCESS] Downloaded playit.exe successfully."

        $playitProcess = Start-Process -FilePath ".\playit.exe" -ArgumentList "--secret ${{ secrets.PL }}" -PassThru -WindowStyle Hidden
        # STABILITY FIX: Use 'High' priority instead of 'Realtime' to prevent system freezes.
        $playitProcess.PriorityClass = "High"
        Write-Host "[SUCCESS] Playit tunnel agent started with HIGH priority (PID: $($playitProcess.Id))."
        
    - name: Display Connection Info & Maintain Session
      shell: powershell
      run: |
        Write-Host "[*] Waiting for tunnel to establish..."
        Start-Sleep -s 15
        
        Write-Host "
        ****************************************************
        ** STABLE PERFORMANCE RDP IS READY            **
        ****************************************************
        
        Connect using the TCP address from your Playit dashboard:
        https://playit.gg/account/tunnels
        
        Your system is now optimized for STABLE performance.
        This session will remain active for the job duration.
        "
        Start-Sleep -Seconds 21000
